# Generated by Django 5.2.1 on 2025-07-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_entry', models.CharField(max_length=500)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Puns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puns_text', models.CharField(max_length=250)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughts_text', models.CharField(max_length=250)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
